# Generated by Django 3.2.17 on 2023-09-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20230902_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecode',
            name='type',
            field=models.CharField(choices=[('serial', 'SERIAL'), ('upc', 'UPC'), ('manufacture', 'Manufacture'), ('serial', 'SERIAL')], default='upc', max_length=256),
        ),
        migrations.AlterField(
            model_name='tabledocument',
            name='type',
            field=models.CharField(choices=[('image', 'IMAGE'), ('pdf', 'PDF'), ('qrcode', 'QRCODE'), ('unknown', 'UNKNOWN')], default='image', max_length=50),
        ),
    ]
