# Generated by Django 3.2.17 on 2023-09-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20230920_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledocument',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
