# Generated by Django 3.2.17 on 2023-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_tabledocument_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecode',
            name='type',
            field=models.CharField(choices=[('serial', 'SERIAL'), ('upc', 'UPC'), ('manufacture', 'Manufacture')], default='upc', max_length=256),
        ),
    ]
