# Generated by Django 3.2.17 on 2023-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menudocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudocument',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
