# Generated by Django 3.2.17 on 2023-10-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menudocument_is_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
