# Generated by Django 3.2.17 on 2023-09-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='extra_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartline',
            name='extra_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
