#!/bin/sh

# Apply database migrations
python manage.py migrate

# Collect static files
python manage.py collectstatic --noinput

# Start the Django development server
gunicorn conf.wsgi:application -b 0.0.0.0:8080 --reload