from django.urls import path

from .viewsets import (
    AttributeListCreateAPIView,
    AttributeRetrieveUpdateDestroyAPIView,
    AttributeGroupListCreateAPIView,
    AttributeGroupRetrieveUpdateDestroyAPIView,
    BrandListCreateAPIView,
    BrandRetrieveUpdateDestroyAPIView,
    DocumentListCreateAPIView,
    DocumentRetrieveUpdateDestroyAPIView,
    GroupListCreateAPIView,
    GroupRetrieveUpdateDestroyAPIView,
    ProductAttributeListCreateAPIView,
    ProductAttributeRetrieveUpdateDestroyAPIView,
    ProductCodeListCreateAPIView,
    ProductCodeQRCodeCreateAPIView,
    ProductCodeRetrieveUpdateDestroyAPIView,
    ProductDocumentListCreateAPIView,
    ProductDocumentRetrieveUpdateDestroyAPIView,
    ProductDocumentUploadAPIView,
    ProductListCreateAPIView,
    ProductPriceListCreateAPIView,
    ProductPriceRetrieveUpdateDestroyAPIView,
    ProductQRCodeCreateAPIView,
    ProductRetrieveUpdateDestroyAPIView,
    ProductSearchAPIView,
    ProductUnitListCreateAPIView,
    ProductUnitRetrieveUpdateDestroyAPIView,
    ProductVatListCreateAPIView,
    ProductVatRetrieveUpdateDestroyAPIView,
    ProductWarehouseListCreateAPIView,
    ProductWarehouseRetrieveUpdateDestroyAPIView,
    SupplierListCreateAPIView,
    SupplierRetrieveUpdateDestroyAPIView,
    TypeListCreateAPIView,
    TypeRetrieveUpdateDestroyAPIView,
    UnitListCreateAPIView,
    UnitRetrieveUpdateDestroyAPIView,
    VatListCreateAPIView,
    VatRetrieveUpdateDestroyAPIView,
    WarehouseListCreateAPIView,
    WarehouseRetrieveUpdateDestroyAPIView,
)

app_name = "v1"

urlpatterns = [
    # path('get-advanced-search-data/', get_advanced_search_data, name='get_advanced_search_data'),
    # path('get-products/', get_products, name='get_products'),
    path(
        "attribute-groups/",
        AttributeGroupListCreateAPIView.as_view(),
        name="attribute-group_list_create",
    ),
    path(
        "attribute-groups/<uuid:uuid>/",
        AttributeGroupRetrieveUpdateDestroyAPIView.as_view(),
        name="attribute-group_retrieve_update_delete",
    ),
    path(
        "attributes/",
        AttributeListCreateAPIView.as_view(),
        name="attribute_list_create",
    ),
    path(
        "attributes/<uuid:uuid>/",
        AttributeRetrieveUpdateDestroyAPIView.as_view(),
        name="attribute_retrieve_update_delete",
    ),
    path("brands/", BrandListCreateAPIView.as_view(), name="brand_list_create"),
    path(
        "brands/<uuid:uuid>/",
        BrandRetrieveUpdateDestroyAPIView.as_view(),
        name="brand_retrieve_update_delete",
    ),
    path(
        "documents/", DocumentListCreateAPIView.as_view(), name="document_list_create"
    ),
    path(
        "documents/<uuid:uuid>/",
        DocumentRetrieveUpdateDestroyAPIView.as_view(),
        name="document_retrieve_update_delete",
    ),
    path("groups/", GroupListCreateAPIView.as_view(), name="group_list_create"),
    path(
        "groups/<uuid:uuid>/",
        GroupRetrieveUpdateDestroyAPIView.as_view(),
        name="group_retrieve_update_delete",
    ),
    path("products/", ProductListCreateAPIView.as_view(), name="product_list_create"),
    path(
        "products/<uuid:uuid>/",
        ProductRetrieveUpdateDestroyAPIView.as_view(),
        name="product_retrieve_update_delete",
    ),
    path(
        "products/<uuid:uuid>/create-qr-code/",
        ProductQRCodeCreateAPIView.as_view(),
        name="product-create-qr-code",
    ),
    path(
        "products/<uuid:product_uuid>/codes/",
        ProductCodeListCreateAPIView.as_view(),
        name="product-code_list_create",
    ),
    path(
        "products/<uuid:product_uuid>/codes/<uuid:uuid>/",
        ProductCodeRetrieveUpdateDestroyAPIView.as_view(),
        name="product-code_retrieve_update_delete",
    ),
    path(
        "products/<uuid:product_uuid>/codes/<uuid:uuid>/create-qr-code/",
        ProductCodeQRCodeCreateAPIView.as_view(),
        name="product-code-create-qr-code",
    ),
    path(
        "products/<uuid:product_uuid>/documents/",
        ProductDocumentListCreateAPIView.as_view(),
        name="product-document_list_create",
    ),
    path(
        "products/<uuid:product_uuid>/documents/<uuid:uuid>/",
        ProductDocumentRetrieveUpdateDestroyAPIView.as_view(),
        name="product-document_retrieve_update_delete",
    ),
    path(
        "products/<uuid:product_uuid>/prices/",
        ProductPriceListCreateAPIView.as_view(),
        name="product-price_list_create",
    ),
    path(
        "products/<uuid:product_uuid>/prices/<uuid:uuid>/",
        ProductPriceRetrieveUpdateDestroyAPIView.as_view(),
        name="product-price_retrieve_update_delete",
    ),
    path(
        "products/<uuid:product_uuid>/warehouses/",
        ProductWarehouseListCreateAPIView.as_view(),
        name="product-warehouse_list_create",
    ),
    path(
        "products/<uuid:product_uuid>/warehouses/<uuid:uuid>/",
        ProductWarehouseRetrieveUpdateDestroyAPIView.as_view(),
        name="product-warehouse_retrieve_update_delete",
    ),
    path(
        "products/<uuid:product_uuid>/attributes/",
        ProductAttributeListCreateAPIView.as_view(),
        name="product-attribute_list_create",
    ),
    path(
        "products/<uuid:product_uuid>/attributes/<uuid:uuid>/",
        ProductAttributeRetrieveUpdateDestroyAPIView.as_view(),
        name="product-attribute_retrieve_update_delete",
    ),
    path(
        "products/<uuid:product_uuid>/units/",
        ProductUnitListCreateAPIView.as_view(),
        name="product-unit_list_create",
    ),
    path(
        "products/<uuid:product_uuid>/units/<uuid:uuid>/",
        ProductUnitRetrieveUpdateDestroyAPIView.as_view(),
        name="product-unit_retrieve_update_delete",
    ),
    path(
        "products/<uuid:product_uuid>/vats/",
        ProductVatListCreateAPIView.as_view(),
        name="product-vat_list_create",
    ),
    path(
        "products/<uuid:product_uuid>/vats/<uuid:uuid>/",
        ProductVatRetrieveUpdateDestroyAPIView.as_view(),
        name="product-vat_retrieve_update_delete",
    ),
    path(
        "suppliers/", SupplierListCreateAPIView.as_view(), name="supplier_list_create"
    ),
    path(
        "suppliers/<uuid:uuid>/",
        SupplierRetrieveUpdateDestroyAPIView.as_view(),
        name="supplier_retrieve_update_delete",
    ),
    path("types/", TypeListCreateAPIView.as_view(), name="type_list_create"),
    path(
        "types/<uuid:uuid>/",
        TypeRetrieveUpdateDestroyAPIView.as_view(),
        name="type_retrieve_update_delete",
    ),
    path(
        "warehouses/",
        WarehouseListCreateAPIView.as_view(),
        name="warehouse_list_create",
    ),
    path(
        "warehouses/<uuid:uuid>/",
        WarehouseRetrieveUpdateDestroyAPIView.as_view(),
        name="warehouse_retrieve_update_delete",
    ),
    path(
        "units/",
        UnitListCreateAPIView.as_view(),
        name="unit_list_create",
    ),
    path(
        "units/<uuid:uuid>/",
        UnitRetrieveUpdateDestroyAPIView.as_view(),
        name="unit_retrieve_update_delete",
    ),
    path(
        "vats/",
        VatListCreateAPIView.as_view(),
        name="vat_list_create",
    ),
    path(
        "vats/<uuid:uuid>/",
        VatRetrieveUpdateDestroyAPIView.as_view(),
        name="vat_retrieve_update_delete",
    ),
    path("products/search/", ProductSearchAPIView.as_view(), name="product-search"),
    path(
        "products/<uuid:product_uuid>/upload-document/",
        ProductDocumentUploadAPIView.as_view(),
        name="product_document_upload",
    ),
]
