# Generated by Django 3.1.5 on 2022-12-17 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0038_auto_20221030_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sub_total', models.DecimalField(decimal_places=6, default='00.00', max_digits=15)),
                ('discount', models.DecimalField(decimal_places=6, default='00.00', max_digits=15)),
                ('tax', models.DecimalField(decimal_places=6, default='00.00', max_digits=15)),
                ('total', models.DecimalField(decimal_places=6, default='00.00', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('canceled', 'CANCELED'), ('refund', 'REFUND')], default='pending', max_length=256)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_products', to='inventory.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=6, default='00.00', max_digits=15)),
                ('price', models.DecimalField(decimal_places=6, default='00.00', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('canceled', 'CANCELED'), ('refund', 'REFUND')], default='pending', max_length=256)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='shop.shoporder')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderlines', to='shop.shopproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeepers', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeepers', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ShopExtraLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=6, default='00.00', max_digits=15)),
                ('price', models.DecimalField(decimal_places=6, default='00.00', max_digits=15)),
                ('type', models.CharField(choices=[('discount', 'DISCOUNT'), ('tax', 'TAX')], default='tax', max_length=256)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('canceled', 'CANCELED'), ('refund', 'REFUND')], default='pending', max_length=256)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extralines', to='shop.shoporder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_shop_name_location'),
        ),
        migrations.AddConstraint(
            model_name='shopproduct',
            constraint=models.UniqueConstraint(fields=('product', 'shop'), name='unique_shopproduct_product_shop'),
        ),
        migrations.AddConstraint(
            model_name='shopkeeper',
            constraint=models.UniqueConstraint(fields=('employee', 'shop'), name='unique_shopkeeper_employee_shop'),
        ),
    ]
