# Generated by Django 3.2.17 on 2023-09-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230908_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='type',
            field=models.CharField(choices=[('image', 'IMAGE'), ('pdf', 'PDF'), ('qrcode', 'QRCODE'), ('unknown', 'UNKNOWN')], default='image', max_length=50),
        ),
    ]
