# Generated by Django 3.2.17 on 2023-03-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productwarehouse',
            old_name='wearhouse',
            new_name='warehouse',
        ),
    ]
