# Generated by Django 3.2.17 on 2023-03-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_wearhouse_productwarehouse_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='type',
            field=models.CharField(choices=[('image', 'IMAGE'), ('pdf', 'PDF'), ('qrcode', 'QRCODE')], default='image', max_length=50),
        ),
    ]
