# Generated by Django 3.2.17 on 2023-04-06 23:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_auto_20230324_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='max',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='min',
        ),
        migrations.RemoveField(
            model_name='vat',
            name='value',
        ),
        migrations.CreateModel(
            name='ProductVat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='This will be exposed to the outside world.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('flat', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
                ('percentage', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productvat_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vats', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productvat_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.vat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='This will be exposed to the outside world.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('max', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
                ('min', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productunit_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productunit_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
