# Generated by Django 3.2.17 on 2024-01-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_placed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('food_preparation', 'Food Preparation'), ('food_ready', 'Food Ready'), ('out_for_delivery', 'Out for Delivery'), ('on_your_table', 'On Your Table'), ('ready_to_indulge', 'Ready to Indulge'), ('payment_ready', 'Payment Ready'), ('payment_done', 'Payment Done'), ('canceled', 'Canceled')], default='order_placed', max_length=50),
        ),
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('food_preparation', 'Food Preparation'), ('food_ready', 'Food Ready'), ('out_for_delivery', 'Out for Delivery'), ('on_your_table', 'On Your Table'), ('ready_to_indulge', 'Ready to Indulge'), ('payment_ready', 'Payment Ready'), ('payment_done', 'Payment Done'), ('canceled', 'Canceled')], default='order_placed', max_length=50),
        ),
    ]
