# Generated by Django 3.2.17 on 2024-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_placed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('payment_pending', 'Payment pending'), ('new', 'New'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('payment_pending', 'Payment pending'), ('new', 'New'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='created', max_length=50),
        ),
    ]
