# Generated by Django 3.1.5 on 2023-01-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopextraline',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
    ]
