# Generated by Django 3.1.5 on 2023-02-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopextraline_is_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone_numbers',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
