from django.urls import path

from .viewsets import (
    AttributeListCreateAPIView,
    AttributeRetrieveUpdateDestroyAPIView,
    AttributeGroupListCreateAPIView,
    AttributeGroupRetrieveUpdateDestroyAPIView,
    BrandListCreateAPIView,
    BrandRetrieveUpdateDestroyAPIView,
    DocumentListCreateAPIView,
    DocumentRetrieveUpdateDestroyAPIView,
    GroupListCreateAPIView,
    GroupRetrieveUpdateDestroyAPIView,
    ProductAttributeListCreateAPIView,
    ProductAttributeRetrieveUpdateDestroyAPIView,
    ProductCodeListCreateAPIView,
    ProductCodeQRCodeCreateAPIView,
    ProductCodeRetrieveUpdateDestroyAPIView,
    ProductDocumentListCreateAPIView,
    ProductDocumentRetrieveUpdateDestroyAPIView,
    ProductListCreateAPIView,
    ProductPriceListCreateAPIView,
    ProductPriceRetrieveUpdateDestroyAPIView,
    ProductQRCodeCreateAPIView,
    ProductRetrieveUpdateDestroyAPIView,
    ProductUnitListCreateAPIView,
    ProductUnitRetrieveUpdateDestroyAPIView,
    ProductVatListCreateAPIView,
    ProductVatRetrieveUpdateDestroyAPIView,
    ProductWarehouseListCreateAPIView,
    ProductWarehouseRetrieveUpdateDestroyAPIView,
    SupplierListCreateAPIView,
    SupplierRetrieveUpdateDestroyAPIView,
    TypeListCreateAPIView,
    TypeRetrieveUpdateDestroyAPIView,
    UnitListCreateAPIView,
    UnitRetrieveUpdateDestroyAPIView,
    VatListCreateAPIView,
    VatRetrieveUpdateDestroyAPIView,
    WarehouseListCreateAPIView,
    WarehouseRetrieveUpdateDestroyAPIView,
)

app_name = "v1"

urlpatterns = [
    # path('get-advanced-search-data/', get_advanced_search_data, name='get_advanced_search_data'),
    # path('get-products/', get_products, name='get_products'),
    path(
        "attribute-groups/",
        AttributeGroupListCreateAPIView.as_view(),
        name="attribute-group-list-create",
    ),
    path(
        "attribute-groups/<uuid:uuid>/",
        AttributeGroupRetrieveUpdateDestroyAPIView.as_view(),
        name="attribute-group-retrieve-update-delete",
    ),
    path(
        "attributes/",
        AttributeListCreateAPIView.as_view(),
        name="attribute-list-create",
    ),
    path(
        "attributes/<uuid:uuid>/",
        AttributeRetrieveUpdateDestroyAPIView.as_view(),
        name="attribute-retrieve-update-delete",
    ),
    path("brands/", BrandListCreateAPIView.as_view(), name="brand-list-create"),
    path(
        "brands/<uuid:uuid>/",
        BrandRetrieveUpdateDestroyAPIView.as_view(),
        name="brand-retrieve-update-delete",
    ),
    path(
        "documents/", DocumentListCreateAPIView.as_view(), name="document-list-create"
    ),
    path(
        "documents/<uuid:uuid>/",
        DocumentRetrieveUpdateDestroyAPIView.as_view(),
        name="document-retrieve-update-delete",
    ),
    path("groups/", GroupListCreateAPIView.as_view(), name="group-list-create"),
    path(
        "groups/<uuid:uuid>/",
        GroupRetrieveUpdateDestroyAPIView.as_view(),
        name="group-retrieve-update-delete",
    ),
    path("products/", ProductListCreateAPIView.as_view(), name="product-list-create"),
    path(
        "products/<uuid:uuid>/",
        ProductRetrieveUpdateDestroyAPIView.as_view(),
        name="product-retrieve-update-delete",
    ),
    path(
        "products/<uuid:uuid>/create-qr-code/",
        ProductQRCodeCreateAPIView.as_view(),
        name="product-create-qr-code",
    ),
    path(
        "products/<uuid:product_uuid>/codes/",
        ProductCodeListCreateAPIView.as_view(),
        name="product-code-list-create",
    ),
    path(
        "products/<uuid:product_uuid>/codes/<uuid:uuid>/",
        ProductCodeRetrieveUpdateDestroyAPIView.as_view(),
        name="product-code-retrieve-update-delete",
    ),
    path(
        "products/<uuid:product_uuid>/codes/<uuid:uuid>/create-qr-code/",
        ProductCodeQRCodeCreateAPIView.as_view(),
        name="product-code-create-qr-code",
    ),
    path(
        "products/<uuid:product_uuid>/documents/",
        ProductDocumentListCreateAPIView.as_view(),
        name="product-document-list-create",
    ),
    path(
        "products/<uuid:product_uuid>/documents/<uuid:uuid>/",
        ProductDocumentRetrieveUpdateDestroyAPIView.as_view(),
        name="product-document-retrieve-update-delete",
    ),
    path(
        "products/<uuid:product_uuid>/prices/",
        ProductPriceListCreateAPIView.as_view(),
        name="product-price-list-create",
    ),
    path(
        "products/<uuid:product_uuid>/prices/<uuid:uuid>/",
        ProductPriceRetrieveUpdateDestroyAPIView.as_view(),
        name="product-price-retrieve-update-delete",
    ),
    path(
        "products/<uuid:product_uuid>/warehouses/",
        ProductWarehouseListCreateAPIView.as_view(),
        name="product-warehouse-list-create",
    ),
    path(
        "products/<uuid:product_uuid>/warehouses/<uuid:uuid>/",
        ProductWarehouseRetrieveUpdateDestroyAPIView.as_view(),
        name="product-warehouse-retrieve-update-delete",
    ),
    path(
        "products/<uuid:product_uuid>/attributes/",
        ProductAttributeListCreateAPIView.as_view(),
        name="product-attribute-list-create",
    ),
    path(
        "products/<uuid:product_uuid>/attributes/<uuid:uuid>/",
        ProductAttributeRetrieveUpdateDestroyAPIView.as_view(),
        name="product-attribute-retrieve-update-delete",
    ),
    path(
        "products/<uuid:product_uuid>/units/",
        ProductUnitListCreateAPIView.as_view(),
        name="product-unit-list-create",
    ),
    path(
        "products/<uuid:product_uuid>/units/<uuid:uuid>/",
        ProductUnitRetrieveUpdateDestroyAPIView.as_view(),
        name="product-unit-retrieve-update-delete",
    ),
    path(
        "products/<uuid:product_uuid>/vats/",
        ProductVatListCreateAPIView.as_view(),
        name="product-vat-list-create",
    ),
    path(
        "products/<uuid:product_uuid>/vats/<uuid:uuid>/",
        ProductVatRetrieveUpdateDestroyAPIView.as_view(),
        name="product-vat-retrieve-update-delete",
    ),
    path(
        "suppliers/", SupplierListCreateAPIView.as_view(), name="supplier-list-create"
    ),
    path(
        "suppliers/<uuid:uuid>/",
        SupplierRetrieveUpdateDestroyAPIView.as_view(),
        name="supplier-retrieve-update-delete",
    ),
    path("types/", TypeListCreateAPIView.as_view(), name="type-list-create"),
    path(
        "types/<uuid:uuid>/",
        TypeRetrieveUpdateDestroyAPIView.as_view(),
        name="type-retrieve-update-delete",
    ),
    path(
        "warehouses/",
        WarehouseListCreateAPIView.as_view(),
        name="warehouse-list-create",
    ),
    path(
        "warehouses/<uuid:uuid>/",
        WarehouseRetrieveUpdateDestroyAPIView.as_view(),
        name="warehouse-retrieve-update-delete",
    ),
    path(
        "units/",
        UnitListCreateAPIView.as_view(),
        name="unit-list-create",
    ),
    path(
        "units/<uuid:uuid>/",
        UnitRetrieveUpdateDestroyAPIView.as_view(),
        name="unit-retrieve-update-delete",
    ),
    path(
        "vats/",
        VatListCreateAPIView.as_view(),
        name="vat-list-create",
    ),
    path(
        "vats/<uuid:uuid>/",
        VatRetrieveUpdateDestroyAPIView.as_view(),
        name="vat-retrieve-update-delete",
    ),
]
